# Generated by Django 2.1.1 on 2018-10-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='office',
            field=models.CharField(default='some string', max_length=100),
        ),
        migrations.AddField(
            model_name='politician',
            name='party',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
