# Generated by Django 2.1.1 on 2018-10-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0002_auto_20181005_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='office',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='summary',
        ),
        migrations.AddField(
            model_name='politician',
            name='date_of_birth',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='politician',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='missed_votes',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='missed_votes_pct',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='next_election',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='politician',
            name='phone',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='politician',
            name='state',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='state_rank',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='politician',
            name='title',
            field=models.CharField(default=True, max_length=25),
        ),
        migrations.AddField(
            model_name='politician',
            name='total_votes',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_account',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='url',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='politician',
            name='votes_with_party_pct',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='politician',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='politician',
            name='party',
            field=models.CharField(max_length=10),
        ),
    ]
