# Generated by Django 2.1.1 on 2018-10-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0003_auto_20181009_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='phone',
            field=models.CharField(default=True, max_length=25, null=True),
        ),
    ]
