# Generated by Django 2.1.1 on 2018-10-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0012_auto_20181009_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='next_election',
        ),
    ]
