# Generated by Django 2.1.1 on 2018-10-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0013_remove_politician_next_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='missed_votes_pct',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
