# Generated by Django 2.1.1 on 2018-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0014_auto_20181010_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
