# Generated by Django 2.1.1 on 2018-10-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0014_auto_20181010_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='votes_with_party_pct',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
