# Generated by Django 2.1.1 on 2018-10-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0015_auto_20181010_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='missed_votes_pct',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='votes_with_party_pct',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
