# Generated by Django 2.1.1 on 2018-10-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0016_auto_20181010_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='missed_votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
