# Generated by Django 2.1.1 on 2018-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0019_auto_20181010_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='state_rank',
            field=models.CharField(default=True, max_length=250, null=True),
        ),
    ]
