# Generated by Django 2.1.1 on 2018-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0020_auto_20181010_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='missed_votes_pct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='state_rank',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
