# Generated by Django 2.1.1 on 2018-10-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poli_match_app', '0015_quote_source'),
        ('poli_match_app', '0023_auto_20181010_1644'),
    ]

    operations = [
    ]
